title: Caroline's Website
author: Caroline Egerman
email: cregerman22@gmail.com
description: Caroline's final project for APCSA

# social links
instagram_username: caroline.egerman
github_username: cregerman

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
