title: Caroline's Website
author: Caroline R. Egerman
email: cregerman22@gmail.com
description: APCSA Final Project

# social links
instagram_username: caroline.egerman
snapchat_username: carolineegerman
github_username: cregerman

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
